//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBH.BOS.Web.SentMailServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SentMailServices.ISendMailSvc")]
    public interface ISendMailSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendMailSvc/SendMailCustomizeByTemplate", ReplyAction="http://tempuri.org/ISendMailSvc/SendMailCustomizeByTemplateResponse")]
        bool SendMailCustomizeByTemplate(string title, string subject, string content, string emailRecieve);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendMailSvc/SendMailCustomizeByTemplate", ReplyAction="http://tempuri.org/ISendMailSvc/SendMailCustomizeByTemplateResponse")]
        System.Threading.Tasks.Task<bool> SendMailCustomizeByTemplateAsync(string title, string subject, string content, string emailRecieve);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendMailSvc/SendMailByVerifyMember", ReplyAction="http://tempuri.org/ISendMailSvc/SendMailByVerifyMemberResponse")]
        bool SendMailByVerifyMember(string emailVerify);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendMailSvc/SendMailByVerifyMember", ReplyAction="http://tempuri.org/ISendMailSvc/SendMailByVerifyMemberResponse")]
        System.Threading.Tasks.Task<bool> SendMailByVerifyMemberAsync(string emailVerify);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendMailSvc/SendMailResetPassword", ReplyAction="http://tempuri.org/ISendMailSvc/SendMailResetPasswordResponse")]
        bool SendMailResetPassword(string emailRecieve, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendMailSvc/SendMailResetPassword", ReplyAction="http://tempuri.org/ISendMailSvc/SendMailResetPasswordResponse")]
        System.Threading.Tasks.Task<bool> SendMailResetPasswordAsync(string emailRecieve, string newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISendMailSvcChannel : BBH.BOS.Web.SentMailServices.ISendMailSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendMailSvcClient : System.ServiceModel.ClientBase<BBH.BOS.Web.SentMailServices.ISendMailSvc>, BBH.BOS.Web.SentMailServices.ISendMailSvc {
        
        public SendMailSvcClient() {
        }
        
        public SendMailSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendMailSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMailSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMailSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendMailCustomizeByTemplate(string title, string subject, string content, string emailRecieve) {
            return base.Channel.SendMailCustomizeByTemplate(title, subject, content, emailRecieve);
        }
        
        public System.Threading.Tasks.Task<bool> SendMailCustomizeByTemplateAsync(string title, string subject, string content, string emailRecieve) {
            return base.Channel.SendMailCustomizeByTemplateAsync(title, subject, content, emailRecieve);
        }
        
        public bool SendMailByVerifyMember(string emailVerify) {
            return base.Channel.SendMailByVerifyMember(emailVerify);
        }
        
        public System.Threading.Tasks.Task<bool> SendMailByVerifyMemberAsync(string emailVerify) {
            return base.Channel.SendMailByVerifyMemberAsync(emailVerify);
        }
        
        public bool SendMailResetPassword(string emailRecieve, string newPassword) {
            return base.Channel.SendMailResetPassword(emailRecieve, newPassword);
        }
        
        public System.Threading.Tasks.Task<bool> SendMailResetPasswordAsync(string emailRecieve, string newPassword) {
            return base.Channel.SendMailResetPasswordAsync(emailRecieve, newPassword);
        }
    }
}
